language: php
sudo: false
php:
 - 7.4
 - nightly

jobs:
  allow_failures:
    - php: nightly
 
before_install:
 - export PATH="$PATH:$HOME/.composer/vendor/bin"
 - composer global require friendsofphp/php-cs-fixer:~2.15.0

before_script:
 - chmod +x scripts/tests/syntax.sh
 - chmod +x scripts/tests/codestyle.sh
 - composer update

script:
 - scripts/tests/syntax.sh
 - scripts/tests/codestyle.sh
 - composer test
